### PR TITLE
Remove ./circleci/config.yml file

### PR DESCRIPTION
**Pull request by dsolmirano**
This file is no longer in use

### CODE REVIEW

**Review by marcos-vivar — APPROVED** [review]
LGTM @dsolmirano 👍🏽

**Comment by jbeckert-trustar** [comment]
LGTM

**Review by jbeckert-trustar — APPROVED** [review]

**Comment by jbeckert-trustar** [comment]
Don't you have to disable the required MR checks performed via CircleCI on this repo?

**Comment by dsolmirano** [comment]
> Don't you have to disable the required MR checks performed via CircleCI on this repo?

Yes! I will do that and merge

**Pull request merged**
